### ISSUE TITLE
Stop New version changes page from showing?

### ISSUE THREAD

**Issue by abdulajet** [Phu1237/vscode-vs-browser#27]
Is there a way to disable this behaviour?

**Comment by abdulajet** [comment]
@Phu1237 seems like this is doing it? possible to turn this off? https://github.com/Phu1237/vscode-vs-browser/blob/00dfae82d4a38110c72c3908bd4991fefc86c079/src/extension.ts#L27

**Comment by Phu1237** [comment]
@abdulajet 
I will add a new option to turn this off in the new version
I will inform you when this option is available
Thank you for your suggestion!

**Comment by Phu1237** [comment]
@abdulajet 
I haven't thought about it
I will try this when update the new version too

Also, the setting to turn off the "New version changes" page from showing is done but it may take a while because some of my in-progress code is on the branch too (as I'm just working with just 1 branch now 😋)
Maybe it will be available in version 2.1.0 with some newer functions (currently working with switching color scheme for specific website)
Thank you for your good suggestions! 🎉

**Comment by abdulajet** [comment]
@Phu1237 thank you very much!

**Comment by Phu1237** [comment]
@abdulajet 
Understood!
I will try to release a new version to support this by today or tomorrow at the latest as the new WIP function has some problems now
Thank you for using my extension! 😋

**Comment by Phu1237** [comment]
@abdulajet 
Sorry for the late update due to my schedule

I have published version v2.1.0 to the marketplace that contains this setting
**Also I have changed some setting names so it may not get your old setting so please take a look at your settings**
I have added an example settings so you can copy and paste it to your project here: https://github.com/Phu1237/vscode-vs-browser/blob/master/example/.vscode/settings.json
Thank you for using my extension and feel free to suggest more functions if you have the ideas! 🎉

**Comment by abdulajet** [comment]
Awesome @Phu1237 thank you! ill test it and let you know

**Comment by Phu1237** [comment]
@abdulajet 
Thanks! I hope that will meet your needs!

**Comment by abdulajet** [comment]
@Phu1237 works great! thank you
